set -g prefix C-q
unbind C-b
setw -g mode-keys vi
set -g history-limit 5000
set -g visual-activity on
set -g monitor-activity on
set -g default-terminal screen-256color
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

if -b '[ "$XDG_SESSION_TYPE" = x11 ]' {
  if -b 'which xsel &> /dev/null' {
    set -g mouse on
    set -g copy-command "xsel -pi && xsel -po | xsel -bi"
    set -g @paste-command "xsel -bo | tmux load-buffer - ; tmux paste-buffer"
    bind -n MouseDown3Pane run "#{@paste-command}"
    bind ] run "#{@paste-command}"
  }
}

if -b '[ "$XDG_SESSION_TYPE" = wayland ]' {
  if -b 'which wl-copy wl-paste &> /dev/null' {
    set -g mouse on
    set -g copy-command "wl-copy"
    set -g @paste-command "wl-paste | tmux load-buffer - ; tmux paste-buffer"
    bind -n MouseDown3Pane run "#{@paste-command}"
    bind ] run "#{@paste-command}"
  }
}

if -b 'which fzf &> /dev/null' {
  FZF_TMUX=1
  FZF_TMUX_OPTS="-p 90%"

  if -b 'which fzf-ip fzf-pensnippet &> /dev/null' {
    bind i run -b 'tmux send "$(fzf-ip || exit 0)"'
    bind v run -b 'tmux send "$(fzf-pensnippet || exit 0)"'
  }
}

if -b 'which spawn-shell &> /dev/null' {
  bind r run -b spawn-shell
}
