set -g prefix C-q
unbind C-b
setw -g mode-keys vi
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set-option -g default-terminal screen-256color
set-option -g history-limit 5000
set -g visual-activity on
set -g monitor-activity on
set -g mouse on
bind -T root MouseDown3Pane paste-buffer


bind r \
  send "`which python python3 python2 | head -n 1` -c 'import pty;pty.spawn(\"/bin/bash\")'" Enter \;\
  run "sleep 0.5" \;\
  send C-z \;\
  send "stty raw -echo" Enter \;\
  send "fg" Enter \;\
  send "reset" Enter \;\
  send "export TERM=xterm" Enter \;\
  run "tmux send \"stty rows #{pane_height} columns #{pane_width}\" Enter" \;\
  send "alias ls='ls -alt --time-style long-iso'" Enter
