#!/usr/bin/python3

from argparse import ArgumentParser
from pathlib import Path
import subprocess


def install(blacklist: list[str]):
    dotfiles = Path(__file__).parent
    blacklist = [dotfiles / b for b in blacklist]

    for src in dotfiles.glob("**"):
        if src.is_file() and not any(src.full_match(b) for b in blacklist):
            dst = Path.home() / src.relative_to(dotfiles)
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.unlink(True)
            dst.symlink_to(src)


def submodule():
    command = ["git", "submodule", "update", "--init", "--force", "--remote"]
    cwd = Path(__file__).parent
    subprocess.run(command, cwd=cwd)


BLACKLIST = [
    Path(__file__).name,
    ".git/**",
    ".gitmodules",
    "**/.gitignore",
    "misc/**",
]


def main():
    parser = ArgumentParser()
    parser.add_argument("-i", "--install", action="store_true")
    parser.add_argument("-s", "--submodule", action="store_true")
    args = parser.parse_args()

    if not args.install and not args.submodule:
        args.install = args.submodule = True

    if args.install:
        install(BLACKLIST)

    if args.submodule:
        submodule()


if __name__ == "__main__":
    main()
