console_palette: dark
console_mouse: false
console_focus_follow: true
web_open_browser: false
ssl_insecure: true

scripts: [
  "~/.config/mitmproxy/addons/hurl.py",
  "~/.config/mitmproxy/addons/bopen.py",
]
